apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: diameter-service
spec:
  type: ClusterIP
  ports:
    - port: 3868
      targetPort: 3868
      protocol: TCP
      name: http
  selector:
    app: diameter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diameter
  name: diameter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diameter
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: diameter
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-004/hudson/diameter:latest
          name: diameter
          imagePullPolicy: Always
          ports:
            - containerPort: 3868
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 2
              memory: 500Mi

