apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

configMapGenerator:
- literals:
  - REDIS_HOST=redis-service.redis.svc.cluster.local
  - REDIS_PORT=6379
  - OTEL_SERVICE_NAME=sherlock-api
  - OTEL_CLIENT_HOST=localhost
  - OTEL_CLIENT_PORT=4317
  - OTEL_INSECURE=True
  - GET_MSISDN_PUBLIC_IP_URL=http://35.239.109.41/silent_auth
  - GET_DEVICE_LOCATION_MSISDN=http://35.239.109.41/device_location
  - GET_IN_CALL_STATE_URL=http://35.239.109.41/silent_auth
  name: aaa-3gpp-config

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: configmap.yaml