apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

images:
  - name: us-central1-docker.pkg.dev/sherlock-004/hudson/pcrf
    newName: us-central1-docker.pkg.dev/sherlock-003/hudson/pcrf
    newTag: latest