apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: bss-service
spec:
  type: ClusterIP
  ports:
    - port: 50057
      targetPort: 50057
      protocol: TCP
      name: http
  selector:
    app: bss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bss
  name: bss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bss
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bss
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-004/hudson/bss:latest
          name: bss
          imagePullPolicy: Always
          ports:
            - containerPort: 50057
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 2
              memory: 500Mi

