---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hudson

resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/sherlock-004/hudson/sherlockapi
    newName: 537124973831.dkr.ecr.us-east-1.amazonaws.com/sherlock-api
    newTag: latest

patches:
  - path: ingress.yaml