apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: pcrf-service
spec:
  type: ClusterIP
  ports:
    - port: 50056
      targetPort: 50056
      protocol: TCP
      name: http
  selector:
    app: pcrf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pcrf
  name: pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcrf
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pcrf
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-004/hudson/pcrf:latest
          name: pcrf
          imagePullPolicy: Always
          ports:
            - containerPort: 50056
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 2
              memory: 500Mi
