apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: aaa-3gpp-service
spec:
  type: ClusterIP
  ports:
    - port: 50059
      targetPort: 50059
      protocol: TCP
      name: http
  selector:
    app: aaa-3gpp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aaa-3gpp
  name: aaa-3gpp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaa-3gpp
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aaa-3gpp
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-004/hudson/aaa-3gpp:latest
          name: aaa-3gpp
          imagePullPolicy: Always
          ports:
            - containerPort: 50059
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 2
              memory: 500Mi

