apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: hss-service
spec:
  type: ClusterIP
  ports:
    - port: 50058
      targetPort: 50058
      protocol: TCP
      name: http
  selector:
    app: hss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hss
  name: hss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hss
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hss
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-004/hudson/hss:latest
          name: hss
          imagePullPolicy: Always
          ports:
            - containerPort: 50058
          resources:
            requests:
              cpu: 1
              memory: 200
            limits:
              cpu: 2
              memory: 500
